apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  namespace: ztgov-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: m1.zt.gov.cn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gateway
            port:
              number: 80           
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
  namespace: ztgov-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/tscuite/nginx-lua:1.14.0-3
        name: gateway
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
        - mountPath: /etc/nginx/conf.d
          name: gateway
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: localtime
      - configMap:
          defaultMode: 420
          name: gateway
        name: gateway
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway
  namespace: ztgov-app
spec:
  ports:
  - port: 80
    name: gateway
    protocol: TCP
    targetPort: 80
  selector:
    app: gateway
---
kind: ConfigMap
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: gateway
  namespace: ztgov-app
apiVersion: v1
data:
  app.conf: |-
    server {
        listen 80;
        server_name  _;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Headers' 'Origin, X-Requested-With, Content-Type, Accept';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        location /api/admin/cms/create/createPage/all {
            content_by_lua  '
                 package.cpath = "/usr/local/luajit/lib/lua/5.1/?.so;"
                 local request_method = ngx.var.request_method
                 local arg=nil
                 if request_method == "GET" then
                          arg = ngx.req.get_uri_args()
                 elseif request_method == "POST" then
                          ngx.req.read_body()
                          arg = ngx.req.get_post_args()
                 end;
                 ngx.req.read_body()
                 local data = ngx.req.get_body_data()
                 local cjson = require("cjson")
                 local json = cjson.decode(data)
                 local siteId = json["siteId"]
                 if siteId == 1 then
                     ngx.exec("@lua_api_zhaotong")
                 elseif siteId == 494 then
                    ngx.exec("@lua_api_daguan") 
                 elseif siteId == 506 then
                     ngx.exec("@lua_api_zhaoyang") 
                 elseif siteId == 766 then
                     ngx.exec("@lua_api_yiliang") 
                 elseif siteId == 1164 then
                     ngx.exec("@lua_api_yongshan") 
                 elseif siteId == 1638 then
                     ngx.exec("@lua_api_ludian")    
                 elseif siteId == 4410 then
                     ngx.exec("@lua_api_suijiang") 
                 else
                     ngx.exec("@lua_api_def")
                 end;
           ';
        }
        location /api/admin/cms/create/createStatus {
          if ($arg_siteId = "1"){
            proxy_pass http://ztgov-sscms-daguan.ztgov-app;
          }
          if ($arg_siteId = "494"){
            proxy_pass http://ztgov-sscms-daguan.ztgov-app;
          }
          if ($arg_siteId = "506"){
           proxy_pass http://ztgov-sscms-daguan.ztgov-app;
          }
          if ($arg_siteId = "766"){
            proxy_pass http://ztgov-sscms-daguan.ztgov-app;
          }
          if ($arg_siteId = "1164"){
            proxy_pass http://ztgov-sscms-daguan.ztgov-app;
          }
          if ($arg_siteId = "1638"){
            proxy_pass http://ztgov-sscms-daguan.ztgov-app;
          }
          if ($arg_siteId = "4410"){
            proxy_pass http://ztgov-sscms-daguan.ztgov-app;
          }
          proxy_pass http://ztgovsscms7.ztgov-app;
        }
        location / {
          proxy_pass http://ztgovsscms7.ztgov-app;
        }
        location @lua_api_zhaotong {
           proxy_pass http://ztgovsscms7-zhaotong.ztgov-app;
        }
        location @lua_api_daguan {
           proxy_pass http://ztgovsscms7-daguan.ztgov-app;
        }
        location @lua_api_zhaoyang {
           proxy_pass http://ztgovsscms7-zhaoyang.ztgov-app;
        }
        location @lua_api_yiliang {
           proxy_pass http://ztgovsscms7-yiliang.ztgov-app;
        }
        location @lua_api_yongshan {
           proxy_pass http://ztgovsscms7-yongshan.ztgov-app;
        }
        location @lua_api_ludian {
           proxy_pass http://ztgovsscms7-ludian.ztgov-app;
        }
        location @lua_api_suijiang {
           proxy_pass http://ztgovsscms7-suijiang.ztgov-app;
        }
        location @lua_api_def {
           proxy_pass http://ztgovsscms7.ztgov-app;
        }
    }
